### Default Profile
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: com.firefighter.aenitto.common.namingStrategy.SnakeLowerCasePhysicalNamingStrategy

---
### Test Profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2/aenitto
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
