### Default Profile
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  profiles:
    active: develop # 활성화시킬 프로필
    group: # 포함시킬 하위 프로필명
      develop: develop, developdb

---
### Test Profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2/aenitto
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true

---
### Develop Profile
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        ddl-auto: create
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true

        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    show-sql: 'true'

  session:
    store-type: jdbc

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aenitto.clldsrluk4r4.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: aenitto77
