### Default Profile
spring:
  mvc:
    static-path-pattern: /static/**
  sql:
    init:
      mode: never
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 150MB

  profiles:
    active: develop # 활성화시킬 프로필
    group: # 포함시킬 하위 프로필명
      develop: develop, developdb, awss3, env, fcm

  output:
    ansi:
      enabled: always
---
# awss3
spring:
  config:
    activate:
      on-profile: awss3

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: aenitto-message-image
    credentials:
      access-key: $IMAGE_ACCESS_KEY
      secret-key: $IMAGE_SECRET_KEY

---
## Develop Profile
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'

  session:
    store-type: jdbc
---
spring:
  config:
    activate:
      on-profile: fcm
fcm:
  key:
    path: https://fcm.googleapis.com/v1/projects/aenitto-350c7/messages:send
