spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aenitto.clldsrluk4r4.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: aenitto77

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true

      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
