= 애니또 API
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[Member-API]]
== Member API

[[Member-닉네임-수정]]
=== Member 닉네임 수정

operation::change-nickname[snippets='http-request,http-response,request-fields']

<<<<<<< HEAD
[[Main-API]]
== Main API

//[[함께하는-친구들-리스트-가져오기]]
=== 함께하는 친구들 가져오기 API

operation::함께하는 친구들 리스트[snippets='http-request,http-response,path-parameters,response-fields']


=== 방 상태 조회

operation::방 상태 조회[snippets='path-parameters,http-request,http-response,response-fields']
=======
== 마니또 시작하기
operation::마니또 시작하기[snippets='path-parameters,request-headers,http-request,http-response']

== 방 상태 조회
operation::방 상태 조회[snippets='path-parameters,request-headers,http-request,http-response,response-fields']

== 방 정보 조회
operation::방 정보 조회[snippets='path-parameters,http-request,http-response,response-fields']
>>>>>>> develop

== 마니또 시작하기

operation::마니또 시작하기[snippets='path-parameters,http-request,http-response']


== 방 생성
<<<<<<< HEAD

operation::방 생성[snippets='http-request,request-fields,http-response']

== 방 참여

operation::방 참여[snippets='path-parameters,http-request,request-fields,http-response']

== 참여 중인 방 조회

operation::참여 중인 방 조회[snippets='request-parameters,http-request,http-response,response-fields']

== 초대코드 검증

operation::초대코드 검증[snippets='http-request,request-fields,http-response,response-fields']
=======
operation::방 생성[snippets='request-headers,http-request,request-fields,http-response']

== 방 참여
operation::방 참여[snippets='path-parameters,request-headers,http-request,request-fields,http-response']

== 참여 중인 방 조회
operation::참여 중인 방 조회[snippets='request-parameters,request-headers,http-request,http-response,response-fields']

== 초대코드 검증
operation::초대코드 검증[snippets='request-headers,http-request,request-fields,http-response,response-fields']
>>>>>>> develop
