= 애니또 API
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[Member-API]]
== Auth API
=== 회원가입 및 로그인
operation::회원가입 및 로그인[snippets='http-request,http-response,request-fields,response-fields']


[[Auth-API]]
== Member API

[[Member-닉네임-수정]]
=== Member 닉네임 수정
operation::change-nickname[snippets='http-request,http-response,request-fields']

[[Main-API]]
== Main API
=== 함께하는 친구들 가져오기 API
operation::함께하는 친구들 리스트[snippets='http-request,http-response,path-parameters,response-fields']

[[Room-API]]
== Room API

=== 마니또 시작하기
operation::마니또 시작하기[snippets='path-parameters,request-headers,http-request,http-response']

=== 방 상태 조회
operation::방 상태 조회[snippets='path-parameters,request-headers,http-request,http-response,response-fields']

=== 방 정보 조회
operation::방 정보 조회[snippets='path-parameters,http-request,http-response,response-fields']

=== 방 삭제
operation::방 삭제[snippets='path-parameters,http-request,http-response']

=== 방 수정
operation::방 수정하기[snippets='path-parameters,http-request,request-fields,http-response']

=== 방 생성
operation::방 생성[snippets='request-headers,http-request,request-fields,http-response']

=== 방 참여
operation::방 참여[snippets='path-parameters,request-headers,http-request,request-fields,http-response']

=== 참여 중인 방 조회
operation::참여 중인 방 조회[snippets='request-parameters,request-headers,http-request,http-response,response-fields']

=== 초대코드 검증
operation::초대코드 검증[snippets='request-headers,http-request,request-fields,http-response,response-fields']

[[Message-API]]
== 메시지 API
=== 보낸 메시지 가져오기
operation::보낸 메시지 가져오기[snippets='path-parameters,request-headers,http-request,http-response']

=== 메세지 읽음으로 상태변경
operation::메세지 읽음으로 상태 변경[snippets='path-parameters,request-headers,http-request,http-response']

=== 받은 메시지 가져오기
operation::받은 메시지 가져오기[snippets='path-parameters,request-headers,http-request,http-response']

=== 추억 가져오기
operation::추억 가져오기[snippets='path-parameters,request-headers,http-request,http-response']
