= 애니또 API
:toc: left

:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:sectlinks:

[[Member-API]]
== Auth API
=== 회원가입 및 로그인V1
operation::회원가입 및 로그인V1[snippets='http-request,request-fields']
==== 성공 response
operation::회원가입 및 로그인V1[snippets='http-response,response-fields']
==== 실패 response1 - 유효하지 않은 identityToken
operation::회원가입 및 로그인V1 - 실패 (유효하지 않은 identityToken)[snippets='http-response']


=== 회원가입 및 로그인V2
operation::회원가입 및 로그인V2[snippets='http-request,http-response,request-fields,response-fields']
=== 토큰 재발급
operation::토큰 재발급[snippets='http-request,http-response,request-fields,response-fields']


[[Auth-API]]
== Member API

[[Member-닉네임-수정]]
=== Member 닉네임 수정
operation::change-nickname[snippets='http-request,request-fields']
==== 성공 response
operation::change-nickname[snippets='http-response']
==== 실패 response1 - 닉네임 4자 이상
operation::닉네임 변경 - 실패 (제약조건을 지키지 않은 경우)[snippets='http-response']
==== 실패 response2 - 존재하지 않는 유저
operation::닉네임 변경 - 실패 (존재하지 않는 유저의 경우)[snippets='http-response']


[[Main-API]]
== Main API
=== 함께하는 친구들 가져오기 API
operation::함께하는 친구들 리스트[snippets='http-request,http-response,path-parameters,response-fields']

[[Room-API]]
== Room API

=== 마니또 시작하기
operation::마니또 시작하기[snippets='path-parameters,request-headers,http-request,http-response,response-fields']

=== 방 상태 조회
operation::방 상태 조회[snippets='path-parameters,request-headers,http-request,http-response,response-fields']

=== 방 정보 조회
operation::방 정보 조회[snippets='path-parameters,http-request,http-response,response-fields']

=== 방 삭제
operation::방 삭제[snippets='path-parameters,http-request,http-response']

=== 방 수정
operation::방 수정하기[snippets='path-parameters,http-request,request-fields,http-response']

=== 방 생성
operation::방 생성[snippets='request-headers,http-request,request-fields,http-response']

=== 방 참여
operation::방 참여[snippets='path-parameters,request-headers,http-request,request-fields,http-response']

=== 참여 중인 방 조회
operation::참여 중인 방 조회[snippets='request-parameters,request-headers,http-request,http-response,response-fields']

=== 초대코드 검증
operation::초대코드 검증[snippets='request-headers,http-request,request-fields,http-response,response-fields']

[[Message-API]]
== 메시지 API

=== 메세지 보내기
//operation::메세지 생성 - 성공[snippets='http-request']
==== 성공 response
operation::메세지 생성 - 성공[snippets='http-response']
==== 실패 response1 - 내 마니띠가 아님
operation::메세지 생성 - 실패 (내 마니띠가 아님)[snippets='http-response']
==== 실패 response2 - 참여하고 있지 않은 방
operation::메세지 생성 - 실패 (참여하고 있지 않은 방)[snippets='http-response']
==== 실패 response3 - 이미지 확장자가 존재하지 않음
operation::메세지 생성 - 실패 (확장자가 존재하지 않음)[snippets='http-response']
==== 실패 response4 - 제약 조건을 지키지 않음
operation::메세지 생성 - 실패 (제약 조건을 지키지 않음)[snippets='http-response']

=== 보낸 메시지 가져오기
operation::보낸 메시지 가져오기[snippets='path-parameters,request-headers,http-request']
==== 성공 response
operation::보낸 메시지 가져오기[snippets='http-response']
==== 실패 response1 - 마니띠가 존재하지 않음
operation::보낸 메시지 가져오기 - 실패 (마니띠가 존재하지 않음)[snippets='http-response']
==== 실패 response2 - 참여중인 방이 아님
operation::보낸 메시지 가져오기 - 실패 (참여중인 방이 아님)[snippets='http-response']

=== 메세지 읽음으로 상태변경 -> deprecated
operation::메세지 읽음으로 상태 변경[snippets='path-parameters,request-headers,http-request,http-response']

=== 받은 메시지 가져오기
operation::받은 메시지 가져오기[snippets='path-parameters,request-headers,http-request']
==== 성공 response
operation::받은 메시지 가져오기[snippets='http-response']
===== 실패 response1 - 마니띠가 존재하지 않음
operation::받은 메시지 가져오기 - 실패 (마니띠가 존재하지 않음)[snippets='http-response']
===== 실패 response2 - 참여중인 방이 아님
operation::받은 메시지 가져오기 - 실패 (참여중인 방이 아님)[snippets='http-response']


=== 추억 가져오기
operation::추억 가져오기[snippets='path-parameters,request-headers,http-request,http-response']
