= 애니또 API
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

// 예시 템플릿
//[[Member-API]]
//== Member API
//
//[[Member-단일-조회]]
//=== Member 단일 조회
//operation::member-get[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-단일-조회]]
=== Member 단일 조회
operation::temp-login[snippets='http-request,path-parameters,http-response,response-fields']

[[Member-API]]
== Member API
[[Member-닉네임-수정]]
=== Member 닉네임 수정
operation::change-nickname[snippets='http-request,http-response,request-fields']

== 마니또 시작하기
operation::마니또 시작하기[snippets='path-parameters,request-headers,http-request,http-response']

== 방 상태 조회
operation::방 상태 조회[snippets='path-parameters,request-headers,http-request,http-response,response-fields']

== 방 정보 조회
operation::방 정보 조회[snippets='path-parameters,http-request,http-response,response-fields']

== 방 생성
operation::방 생성[snippets='request-headers,http-request,request-fields,http-response']

== 방 참여
operation::방 참여[snippets='path-parameters,request-headers,http-request,request-fields,http-response']

== 방 삭제
operation::방 삭제[snippets='path-parameters,http-request,http-response']

== 방 수정
operation::방 수정하기[snippets='path-parameters,http-request,request-fields,http-response']

== 참여 중인 방 조회
operation::참여 중인 방 조회[snippets='request-headers,http-request,http-response,response-fields']

== 초대코드 검증
operation::초대코드 검증[snippets='request-headers,http-request,request-fields,http-response,response-fields']