name: Deploy

on:
  push:
    branches: [ develop, main ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: aenitto-deploy

jobs:
  deploy:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: properties 생성
        run: echo "${{ secrets.PROPERTIES }}" > ${{ env.PROPERTIES }}
        env:
          PROPERTIES: src/main/resources/application.yml

      - name: firebase.json 생성
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "firebase_service_key.json"
          json: ${{ secrets.FIREBASE_SERVICE_KEY }}
          dir: 'src/main/resources/'

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build --info

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./aenitto-${{ github.ref_name }}.zip ./build/libs/*.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # S3 Bucket으로 copy
      - name: Upload to S3
        run: |
          aws s3 cp --region ${{ env.AWS_REGION }} ./aenitto-${{ github.ref_name }}.zip s3://${{ env.S3_BUCKET_NAME }}/
